name: broadcast_events
description: Enables you to broadcast global events in your app. Helpful in cases where your modules/components need to know about a change happened somewhere in your app. 

version: 2.0.0

author: Devashish Puri <devashishpuri@gmail.com>

homepage: https://github.com/devashishpuri/broadcast_events

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
